name: wine-quality-mlproject
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.7
  - pip
  - pip:
    - pandas==2.2.2
    - numpy==1.26.4
    - scikit-learn==1.5.1
    - mlflow==3.5.1
    - dagshub==0.3.36
    - matplotlib==3.9.1
    - seaborn==0.13.2
